### ISSUE TITLE
Invalid enrolment QR code for custom site.

### ISSUE THREAD

**Issue by StephanGocht** [Tiqr/tiqr-app-ios#33]
Hi,

I am using the tiqr app for user logins on my website. Everything is working fine with the Android app but it seems that there is a problem with iPhone users getting the error "Invalid enrolment QR code.".

While looking through the source code I noticed that in the [project configuration](https://github.com/Tiqr/tiqr-app-ios/blob/c24bb6c35e6b53b701f792a321c3e9140e42a76d/Tiqr%20Client.xcodeproj/project.pbxproj#L589) we have `TIQR_ENFORCE_CHALLENGE_HOSTS = "tiqr.org,surfconext.nl";` for the release build. Which is used to check the enrolment and authentication URLs in
[isValidEnrollmentURL](https://github.com/Tiqr/tiqr-app-core-ios/blob/77bd82ab3b6f4b6fe2b65ba48c96dd9b29abaf89/Sources/TiqrCoreObjC/Classes/TiqrConfig.m#L121-L145). Doesn't this prevent using the tiqr iOS app for other websites?

Best regards,
Stephan

**Comment by phavekes** [comment]
@StephanGocht  Are you using the current app-store version (3.0.10)?

**Comment by StephanGocht** [comment]
I will have to check with the person reporting the problem (I don't have an iPhone, but I guess I will need to get my hands on one to figure out the problem). But yes, I expect it would be the latest version from the App store. I just realized that this version is a bit older, and the code from back then doesn't even have the code I mentioned, yet. Guess the problem is somewhere else then. But thanks for making the PR, that will probably prevent problems in the future!

**Comment by StephanGocht** [comment]
Closing issue as the potential issue with `TIQR_ENFORCE_CHALLENGE_HOSTS` is fixed in #34 .

**Comment by StephanGocht** [comment]
Just in case someone stumbles over the same issue, I managed to find the cause of the actual problem.

My custom scheme URL looked something like

    tiqrenroll://https://my_domain.com/enroll_info/0ee326110d7

This works well with most browsers, however Safari doesn't like the second `://` and removes the colon `:`, even when copying the link. This results in 

    tiqrenroll://https//my_domain.com/enroll_info/0ee326110d7

which is then rejected as URL by the app when clicking on the link (this does not happen when the QR code is scanned instead of clicking on the link). As a workaround I now use `:` instead of `://`, i.e.,

    tiqrenroll://https:my_domain.com/enroll_info/0ee326110d7

which seems to work for Android and iOS, both when using the custom scheme as well as scanning the QR code.
